### ISSUE TITLE
nv_dma_unmap() is not protected by nv_mem_context->is_callback

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#13]
in nv_dma_unmap(), if NV_DMA_MAPPING is defined, nvidia_p2p_dma_unmap_pages is called, which frees dma_mapping, even without setting nv_mem_context->sg_allocated.

later in nv_mem_put_pages(), sg_free_table() is called if nv_mem_context->sg_allocated!=0, even if NV_DMA_MAPPING is defined, which is incorrect.

**Comment by drossetti** [comment]
I propose to remove the set sg_allocated in all the relevant cases, and have the call to sg_free_table() protected by NV_DMA_MAPPING==0

**Comment by drossetti** [comment]
looking better, the call to sg_free_table() is always need.

but nv_dma_unmap() is not protected by nv_mem_context->is_callback, as in nv_mem_put_pages().

**Comment by drossetti** [comment]
changing synopsis

**Comment by drossetti** [comment]
minor issue, nv_mem_put_pages does not set sg_allocated = 0

**Comment by ferasd** [comment]
Right, sg_free_table should be called always since sg_head is allocated in both cases.
nv_mem_context->is_callback protection fix will be pushed.

**Comment by ferasd** [comment]
https://github.com/Mellanox/nv_peer_memory/pull/16

**Comment by ferasd** [comment]
#20

**Comment by drossetti** [comment]
closing
