### ISSUE TITLE
leaking p2p_dma_mapping objects during buffer invalidations

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#14]
nv_get_p2p_free_callback() does not call nvidia_p2p_free_dma_mapping(), necessary to free the P2P DMA mapping.

**Comment by ferasd** [comment]
https://github.com/Mellanox/nv_peer_memory/pull/16

**Comment by ferasd** [comment]
#20

**Comment by drossetti** [comment]
closing as fixed in 1.0-4
