### ISSUE TITLE
invalidation callback relies on undefined behavior of NV driver

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#15]
in nv_get_p2p_free_callback(), a comment shows:
141          /* For now don't set nv_mem_context->page_table to NULL, 
142		  * confirmed by NVIDIA that inflight put_pages with valid pointer will fail gracefully.
143		*/
144	

this is actually a bug in umem.c:peer_umem_release() which can call peer_mem dma_unmap() and put_pages() even if an invalidation callback has freed both the P2P dma mappings and the page_table.

That might have accidentally worked in the past, but it is not correct anymore.

**Comment by drossetti** [comment]
Actually that comment is not in-sync with what the code does.

nv_mem_put_pages() is protected from being called under invalidation by nv_mem_context->is_callback.
issue #13 is about nv_dma_unmap() not being protected in the same way.

So I propose to modify that comment accordingly.

**Comment by ferasd** [comment]
please check #20

**Comment by ferasd** [comment]
@drossetti 
Can we close this ?

**Comment by drossetti** [comment]
fixed
