### ISSUE TITLE
When installing the official 1.0-3 release via debian package, the source in the official tar file is not used.

### ISSUE THREAD

**Issue by JohnSpillerNvidia** [Mellanox/nv_peer_memory#19]
When using build_release.sh to build a debian package, it does not use the source in the nvidia-peer-memory-1.0-3.tar.gz file, but rather uses git to check out a newer version of the source from here.  This causes a few problems:
    1) the apparent source does not necessarily match the package.
    2) since changes have been made since the changelog file was checked in the packages
                nvidia-peer-memory-dkms_1.0-3_all.deb
                nvidia-peer-memory_1.0-3_all.deb
        could be built from any one of the following  commits:
               d93f07d Merge pull request #16 from Mellanox/nv_dma_mapping_fix
               0a39a45 Update nv_peer_mem.c
               d695cb6 Add missing free dma mapping call
               fa142d7 Clear sg_allocated value aftersg page table free
               5029c0d Protect nv_dma_unmap() from p2p_free_callback
               f4e172f Temporary commit to disable nvidia_p2p_dma_map_pages
                a24c818 Roll 1.0-3 release

**Comment by ferasd** [comment]
Today this is the behavior when building the package (rpm or deb)

Hi @alaahl 
I think that we should do the following:
1- By default the script should build the local copy of the module
2- Add a flag that enables cloning the latest version and installing it

**Comment by ferasd** [comment]
please check #20

**Comment by JohnSpillerNvidia** [comment]
Looks good to me.  Now when I go to the official site, I get 1.0-4, and if I start with the 1.0-4 tar file I get 1.0-4.   Do you plan to implement the "grab the latest from head" suggestion?
