### ISSUE TITLE
Debian installation command line error

### ISSUE THREAD

**Issue by byronyi** [Mellanox/nv_peer_memory#24]
I am using Debian 9 (new stable release since 17th June, 2017). According to the Installation part of README.md:

```
$ dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package nvidia-peer-memory
dpkg-buildpackage: info: source version 1.0-4
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Feras Daoud <ferasda@mellanox.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build nv_peer_memory
 fakeroot debian/rules clean
dh clean --with dkms
dh: Compatibility levels before 9 are deprecated (level 8 in use)
   dh_testdir
   dh_clean
dh_clean: Compatibility levels before 9 are deprecated (level 8 in use)
 dpkg-source -b nv_peer_memory
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../nvidia-peer-memory_1.0.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b nv_peer_memory gave error exit status 255
```

A work around: `dpkg-buildpackage -us -uc` needs to be changed into `dpkg-buildpackage -us -uc -b`.

**Comment by ferasd** [comment]
+ @alaahl

**Comment by alaahl** [comment]
Hi @byronyi ,
did you prepare a tarball (named nvidia-peer-memory_1.0.orig.tar.gz ) first ?
it seems like the tarball is missing: 
" dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../nvidia-peer-memory_1.0.orig.tar.{bz2,gz,lzma,xz} "

**Comment by byronyi** [comment]
@alaahl Thanks for the reply. I just found out I download through `curl <link> | tar xz` or clone the directory using `git`. Seems it works only with both tar-ball and source present.
