### ISSUE TITLE
add support for NV dma mappings APIs 

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#3]
New APIs are being added in r361+ drivers. This will allow support for architectures where BARs have bus address != physical address.

APIs are:
typedef struct nvidia_p2p_dma_mapping {
    enum nvidia_p2p_page_size_type page_size_type;
    uint32_t  entries;
    uint64_t *dma_addresses;
} nvidia_p2p_dma_mapping_t;

int nvidia_p2p_dma_map_pages   (struct pci_dev _peer,
           struct nvidia_p2p_page_table *page_table,
           struct nvidia_p2p_dma_mapping *_dma_mapping);
int nvidia_p2p_dma_unmap_pages (struct pci_dev *peer,
             struct nvidia_p2p_page_table *page_table,
             struct nvidia_p2p_dma_mapping *dma_mapping);

Given the presence of struct pci_dev, it might be that NVIDIA-related symvers will change on customer machine, depending on kernel version or even on kernel configuration only. 
That is why shipping a single symvers file within this project is not a solid solution.
A new mechanism will be needed instead.

**Comment by drossetti** [comment]
can you evaluate using symbol_get/symbol_put at runtime to get the actual addresses of the exported nvidia_p2p_* functions?

**Comment by haggaie** [comment]
I think `nv_peer_memory` should be distributed in source format, perhaps with a dkms package to get it to build automatically. That would solve the symvers issue, right?

**Comment by drossetti** [comment]
Judging from http://www.mellanox.com/downloads/ofed/nvidia_peer_memory-1.0-0.tar.gz, you already distribute it in source format.

Two separate new issues:
1) NVIDIA is adding changing the GPUDirect RDMA APIs by enlarging the page table struct (in a backward compatible way) and adding two 2 APIs. One of those is:
int nvidia_p2p_dma_map_pages(struct pci_dev *peer,
        struct nvidia_p2p_page_table *page_table,
        struct nvidia_p2p_dma_mapping **dma_mapping);
 nv_peer_mem is shipping with its own copy of nv-p2p.h so it will not pick the change.
2) in addition, nv_peer_mem is shipping nv.symvers which works only if kernel symbol versions do not change across different NV driver and Linux kernel versions.  
But in particular due to nvidia_p2p_dma_map_pages having a struct pci_dev parameter, symvers will change very often, so shipping nv.symvers does not work anymore.

A possible solution is:
a) during package building, you should pick the currently installed nv-p2p.h from /usr/src/nvidia-X.Y/ and enable the call to the new APIs using the preprocessor macros. This should address n.1 above.
b) stop shipping nv.symvers and start using symbol_get/put to dynamically bind to the nvidia P2P kernel APIs.

**Comment by ferasd** [comment]
pull request ab590fba8efc1e94de454614d7c6740aa52c830c
