### ISSUE TITLE
Have problem installing 

### ISSUE THREAD

**Issue by YuxinxinChen** [Mellanox/nv_peer_memory#35]
Hi, I am using Ubuntu 16.04. From the installation instruction:
```bash
./build_module.sh
 cd /tmp
 tar xzf /tmp/nvidia-peer-memory_1.0.orig.tar.gz
 cd nvidia-peer-memory-1.0
 dpkg-buildpackage -us -uc
 dpkg -i <path to generated deb files>
```
example is given:
```bash
(e.g. dpkg -i nv-peer-memory_1.0-6_all.deb
      dpkg -i nv-peer-memory-dkms_1.0-6_all.deb)
```
However, I didn't find I create any nv-peer-memory_1.0-6_all.deb file during the building process. I am also very confused by the nv-peer-memory_1.0-6_all.deb and nvidia-peer-memory_1.0-6_all.deb. Are they the same? nvidia-peer-memory_1.0-5_all.deb can also work?

Thanks!

Yuxin

**Comment by alaahl** [comment]
Hi @YuxinxinChen 

Please provide a full log of your build.

As for the package names and content:
* **nv-peer-memory**_1.0-6_all.deb --> Installs user-space stuff and tools.
* **nv-peer-memory-dkms**_1.0-6_all.deb)  --> Installs sources and triggers DKMS to compile them and install the built modules.
