### ISSUE TITLE
If connectX-3 HCA can use ibv_reg_mr to register GPU memory created by cudaMalloc?

### ISSUE THREAD

**Issue by YuxinxinChen** [Mellanox/nv_peer_memory#36]
```bash
yuxin420@luigi:~/TEMP/rdma$ lspci -v | grep Mellanox
01:00.0 Network controller: Mellanox Technologies MT27500 Family [ConnectX-3]
	Subsystem: Mellanox Technologies MT27500 Family [ConnectX-3]
82:00.0 Network controller: Mellanox Technologies MT27500 Family [ConnectX-3]
	Subsystem: Mellanox Technologies MT27500 Family [ConnectX-3]
```
I installed Mellanox OFED to use IB verbs. It works fine if the buffer is on CPU memory. But if I ibv_reg_mr to register a buff on GPU, it fails. If I need to use another verb for registering GPU memory or I should do something setting stuff to enable it?

Thanks!

Yuxin

**Comment by ferasd** [comment]
Is nv_peer_mem module loaded?
if so, ibv_reg_mr should work fine.

**Comment by ferasd** [comment]
@YuxinxinChen

**Comment by YuxinxinChen** [comment]
Thank you very much. Problem solved!

**Comment by EsdeathYZH** [comment]
I encounter the same problem, but the nv_peer_mem module has been loaded in my kernel successfully, how do you solve the problem finally?@YuxinxinChen
