### ISSUE TITLE
Can this be used without rdma?

### ISSUE THREAD

**Issue by cliffburdick** [Mellanox/nv_peer_memory#37]
Can this library be used to pass GPU mapped memory to something like dpdk such that the nic would write directly to the GPU memory without RDMA? It seems like it should be as simple as giving dpdk a mempool on the GPU, but it's not clear if this library helps with that.

**Comment by haggaie** [comment]
I believe what you are suggesting should work: this module would enable registering GPU memory in libibverbs, regardless of whether the queue pair using that memory region is an Ethernet QP or an RDMA QP. However, I don't think this idea has been tested so far.

**Comment by cliffburdick** [comment]
For anyone reading this 3 years later, this is now possible using cuVNF:

https://developer.nvidia.com/aerial-sdk
