### ISSUE TITLE
upgrading kernel with nv_peer_mem-1.0-5 breaks on Ubuntu 14.04.5 

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#39]
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-116-generic x86_64)
...
[76463.688316] nv_peer_mem: disagrees about version of symbol ib_register_peer_memory_client
[76463.688326] nv_peer_mem: Unknown symbol ib_register_peer_memory_client (err -22)

this is from nvidia-peer-memory_1.0.5.tar.gz

the problem seems to be that nv_peer_mem/Makefile picks the ofa_kernel symbols from /usr/src/ofa_kernel/default instead of /usr/src/ofa_kernel/$(uname -r).
for some reason, default is not

$ uname -r
4.4.0-116-generic
$ ls -l //usr/src/ofa_kernel/
total 8
drwxr-xr-x 7 root root 4096 Apr  1 17:35 4.4.0-116-generic
drwxr-xr-x 7 root root 4096 Dec  8 18:04 4.4.0-97-generic
lrwxrwxrwx 1 root root   16 Dec  8 18:04 default -> 4.4.0-97-generic
$ ls -l //usr/src/ofa_kernel/default
lrwxrwxrwx 1 root root 16 Dec  8 18:04 //usr/src/ofa_kernel/default -> 4.4.0-97-generic

**Comment by alaahl** [comment]
Hi @drossetti ,
which version are you using ?
This issue has been already addressed in this patch:
 https://github.com/Mellanox/nv_peer_memory/commit/6b5d3d690a73bff7c07d7eaa7369c08fe40637ec 
(available since 1.0-6 release).

Thanks,
Alaa

**Comment by drossetti** [comment]
@JohnSpillerNvidia FYI

**Comment by drossetti** [comment]
@alaahl we need an official release on http://www.mellanox.com/page/products_dyn?product_family=116&mtag=gpudirect.
We don't pick random versions from github. 
thanks

**Comment by alaahl** [comment]
Hi @drossetti 

Sure, we will update it on mellanox website.

**Comment by alaahl** [comment]
Hi @drossetti 

The new release is now available  at:
https://www.mellanox.com/page/products_dyn?product_family=116&mtag=gpudirect&ssn=7dm2tfp197pn1fi5kn0ohdg8u1
