### ISSUE TITLE
rpmbuild --rebuild nvidia_peer_memory-1.0-0.src.rpm is broken on RH 7.x

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#4]
You left the old Makefile version in the nvidia_peer_memory-1.0-0.src.rpm, which is breaking builds for some customers on RH 7.x

**Comment by alaahl** [comment]
Hi @drossetti ,
A new package (nvidia_peer_memory-1.0-1.tar.gz) is avilable at http://www.mellanox.com/page/products_dyn?product_family=116

**Comment by rleon** [comment]
updated the package
