### ISSUE TITLE
make install is broken on RH 7.x

### ISSUE THREAD

**Issue by drossetti** [Mellanox/nv_peer_memory#5]
$ uname -r
3.10.0-327.el7.x86_64

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

$ make install
mkdir -p //lib/modules/3.10.0-327.el7.x86_64/extra/;
cp -f /root/nv_peer_memory/nv_peer_mem.ko //lib/modules/3.10.0-327.el7.x86_64/extra/;
if [ ! -n "" ]; then  -r -ae 3.10.0-327.el7.x86_64;fi;
/bin/sh: -r: command not found
make: *** [install] Error 127

**Comment by haggaie** [comment]
It seems the Makefile doesn't define the `DEPMOD` variable.

@alaahl is that correct?

**Comment by alaahl** [comment]
@haggaie is right.
here is a fix to that: https://github.com/Mellanox/nv_peer_memory/pull/6
