### ISSUE TITLE
insmod: ERROR: could not insert module nv_peer_mem.ko: Invalid parameters in centOS7.5

### ISSUE THREAD

**Issue by Jerrynv** [Mellanox/nv_peer_memory#59]
[dgx@dhcp-10-19-192-252 Jerry]$ cd nv_peer_memory_1.08/
[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ make
[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ sudo insmod nv_peer_mem.ko
[sudo] password for dgx:
insmod: ERROR: could not insert module nv_peer_mem.ko: Invalid parameters

[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ uname -r && cat /etc/*release
3.10.0-862.el7.x86_64
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)
[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ lspci |grep mellanox -i
3e:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
3e:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]

[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ ofed_info|head -1
MLNX_OFED_LINUX-4.7-1.0.0.1 (OFED-4.7-1.0.0):

[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

[dgx@dhcp-10-19-192-252 nv_peer_memory_1.08]$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  418.87.01  Wed Sep 25 06:00:38 UTC 2019

**Comment by e-ago** [comment]
Can you check with dmesg if this is the same issue as in https://github.com/Mellanox/nv_peer_memory/issues/55 ?

**Comment by ferasd** [comment]
Pull request #60 should fix the issue, can you give it a try?

**Comment by ferasd** [comment]
fixed by #60 closing
