### ISSUE TITLE
build_module.sh: tar error about ineffective --exclude parameters

### ISSUE THREAD

**Issue by tzafrir-mellanox** [Mellanox/nv_peer_memory#62]
On Ubuntu 19.10 (tar 1.30+dfsg-6) I get the following error from build_module.sh:

    tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow them.  Please, rearrange them properly.
    tar: --exclude .* has no effect
    tar: --exclude build_release.sh has no effect
    tar: Exiting with failure status due to previous errors

See https://www.gnu.org/software/tar/manual/html_node/Position_002dSensitive-Options.html

**Comment by tzafrir-mellanox** [comment]
Fixed by #61.

**Comment by ferasd** [comment]
fixed by #61 closing
