### ISSUE TITLE
dpkg-buildpackage error

### ISSUE THREAD

**Issue by jzhang82119** [Mellanox/nv_peer_memory#77]
I am following the procedure like below. I got issue when in the step to run "dpkg-buildpackage -us -uc".

Ubuntu 18.04.5 LTS (Bionic Beaver)"  Kernel: 5.4.0-45-generic  
NVIDIA Driver Version: 455.23.05    CUDA Version: 11.1
MLNX_OFED_LINUX-5.1-2.4.6.0

wget https://www.mellanox.com/sites/default/files/downloads/ofed/nvidia-peer-memory_1.1.tar.gz
then untar it,
 cd nvidia_peer_memory-1.1    
 ./build_module.sh
 cd /tmp
 tar xzf /tmp/nvidia-peer-memory_1.1.orig.tar.gz
 cd nvidia-peer-memory-1.1
dpkg-buildpackage -us -uc
 dpkg -i <path to generated deb file>

root@xxxx:/tmp/nvidia-peer-memory-1.1# dpkg-buildpackage -us -uc
dpkg-buildpackage: info: source package nvidia-peer-memory
dpkg-buildpackage: info: source version 1.1-0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Feras Daoud <ferasda@nvidia.com>
dpkg-buildpackage: info: host architecture amd64
dpkg-source --before-build nvidia-peer-memory-1.1
debian/rules clean
dh clean --with dkms
   dh_clean
dpkg-source -b nvidia-peer-memory-1.1
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building nvidia-peer-memory using existing ./nvidia-peer-memory_1.1.orig.tar.gz
patching file dkms.conf
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch 'dkms_name.patch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/dkms_name.patch/ --reject-file=- < nvidia-peer-memory-1.1.orig.83fK3z/debian/patches/dkms_name.patch subprocess returned exit status 1
dpkg-buildpackage: error: dpkg-source -b nvidia-peer-memory-1.1 subprocess returned exit status 2

**Comment by ShrimpLau** [comment]
try to use `dpkg-buildpackage -us -uc -b` instead, in my case, it works
