### ISSUE TITLE
unable to install nvidia-peer-memory-dkms_1.1-0_all.deb

### ISSUE THREAD

**Issue by jzhang82119** [Mellanox/nv_peer_memory#80]
I am getting the following error in the last step from the instruction. What is wrong? I haven't figured out why.
See below

dpkg -i ../nvidia-peer-memory-dkms_1.1-0_all.deb

Selecting previously unselected package nvidia-peer-memory-dkms.
(Reading database ... 249155 files and directories currently installed.)
Preparing to unpack .../nvidia-peer-memory-dkms_1.1-0_all.deb ...
Unpacking nvidia-peer-memory-dkms (1.1-0) ...
Setting up nvidia-peer-memory-dkms (1.1-0) ...
Loading new nvidia-peer-memory-1.1 DKMS files...
Building for 5.4.0-56-generic
Building initial module for 5.4.0-56-generic
Secure Boot not enabled on this system.
Done.

nv_peer_mem:
Running module version sanity check.
- Original module
   - No original module exists within this kernel
- Installation
   - Installing to /lib/modules/5.4.0-56-generic/updates/dkms/

depmod...

DKMS: install completed.
modprobe: ERROR: could not insert 'nv_peer_mem': Unknown symbol in module, or unknown parameter (see dmesg)
dpkg: error processing package nvidia-peer-memory-dkms (--install):
installed nvidia-peer-memory-dkms package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
nvidia-peer-memory-dkms

**Comment by ferasd** [comment]
should be fixed by in latest version #82
